# Generated by Django 3.0.8 on 2020-07-20 03:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=tinymce.models.HTMLField(verbose_name='商品详情'),
        ),
    ]
