# Generated by Django 3.0.8 on 2020-07-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id_default',
            new_name='is_default',
        ),
    ]
